// EASY
// Hash Table String

// Problem
// You are given two strings s and t.
// String t is generated by random shuffling string s and then add
//  one more letter at a random position.
// Return the letter that was added to t.


const findTheDiffrence=(s,t)=>{
    var num = 0;
    for(var i=0;i<t.length;i++){
        num += t[i].charCodeAt(0)
    }
    for(var j=0;j<s.length;j++){
        num -= s[j].charCodeAt(0);
    }
    return String.fromCharCode(num)
}

// Complexity:

//     Time complexity : O(n).
//     Space complexity : O(1).

var findTheDifference = function(s, t) {
    var num = 0;
    for (var i = 0; i < t.length; i++) {
        num ^= t[i].charCodeAt(0);
    }
    for (var j = 0; j < s.length; j++) {
        num ^= s[j].charCodeAt(0);
    }
    return String.fromCharCode(num);
};

// Complexity:

//     Time complexity : O(n).
//     Space complexity : O(1).

